### ISSUE TITLE
Map Related Request

### ISSUE THREAD

**Issue by VaasKahnGrim** [Demonkush/gigabattalion#2]
Regarding the .bsp for this gamemode. I was wondering if by chance we could get an original vmf of it. I myself have been rather interested in making a map for use with the gamemode and I'd like to see how the original map functioned to get a better understanding of it.

Thanks in advance :)

**Comment by Demonkush** [comment]
Here you go!

[gigabat_openspace_vmf.zip](https://github.com/Demonkush/gigabattalion/files/2896505/gigabat_openspace_vmf.zip)

**Comment by VaasKahnGrim** [comment]
thank you, this is very much appreciated :)
